### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AlexArchive** [rowanmiller/EntityFramework.Testing#2]
Hey Rowan.

Is there any documentation or examples of usage for this project? An introductory blog post perhaps? 

p.s. I got damn fucking love this little package!

Thanks.

**Comment by scott-xu** [comment]
@ByteBlast Here you are https://github.com/rowanmiller/EntityFramework.Testing/wiki

**Comment by AlexArchive** [comment]
Whops, my bad. Thanks Scott.
