### ISSUE TITLE
Support for DbSet.Find

### ISSUE THREAD

**Issue by AlexArchive** [rowanmiller/EntityFramework.Testing#3]
At the moment I have to use `Enumerable.SingleOrDefault` instead of `DbSet.Find` because otherwise my tests fail.

It would be nice to have support for `DbSet.Find`.

**Comment by scott-xu** [comment]
It is supported in my fork repo: https://github.com/scott-xu/EntityFramework.Testing
Nuget packages are available as well: https://www.nuget.org/packages/EntityFrameworkTesting.moq

``` C#
mockFooSet.SetupData(fooList, keys => fooList.FirstOrDefault(f => f.Id == keys.First().ToString()));
```

**Comment by rowanmiller** [comment]
Added in https://github.com/rowanmiller/EntityFramework.Testing/commit/4d5a01da72ca6b4e65c330f8a507cbf25d499745

**Comment by rowanmiller** [comment]
Wiki updated with details and changes pushed to NuGet (1.0.0-alpha2)
